name: indi
channels:
  - conda-forge
  - pytorch
dependencies:
  - matplotlib
  - pandas
  - ca-certificates
  - certifi
  - openssl
  - mayavi
  - scipy
  - scikit-learn
  - scikit-image
  - dipy
  - pydicom
  - xarray
  - tqdm
  - pre-commit
  - pyyaml
  - einops
  - hydra-core
  - timm
  - pytest
  - black
  - pywavelets
  - py7zr
  - python-dotenv
  - pyarrow
  - pytorch
  - torchvision
  - torchaudio
  - pytorch
  - opencv
  - pystackreg
  - pip
  - pip:
    - tensorflow
    - itk-elastix
    - pyautogui
    - brukerapi

