# MANUAL SETTINGS

# See documentation for details on all these options.

# ========================================================================================
# WORKFLOWS
# ========================================================================================
# Startup folder
start_folder: /Users/pf/WORK/WORK_2/CIMA_scans/initial_test_scans/vol10
# anon, reg, main
workflow_mode: main
# se, steam
sequence_type: se

# ========================================================================================
# DEBUGGING
# ========================================================================================
# True, False
debug: True
# True, False
registration_extra_debug: False

# ========================================================================================
# IMAGE REGISTRATION
# ========================================================================================
# none, quick_rigid, elastix_rigid, elastix_affine, elastix_non_rigid
# elastix_groupwise (not working well at the moment)
registration: elastix_non_rigid
# fast, slow
registration_speed: fast
# best, groupwise
registration_reference_method: best

# ========================================================================================
# TENSOR FITTING
# ========================================================================================
# LS, WLS, NLLS, RESTORE
tensor_fit_method: NLLS

# ========================================================================================
# IMAGE REMOVAL
# ========================================================================================
# True, False
remove_outliers_manually: True
# True, False
remove_outliers_manually_pre: True
# True, False
# NOT WORKING WELL AT THE MOMENT
remove_outliers_with_ai: False

# ========================================================================================
# MISC
# ========================================================================================
# float in msec
assumed_rr_interval: 1000
# float in msec
calculated_real_b0: 29
# remove slices integers
remove_slices: []


# ========================================================================================
# AI MODELS
# ========================================================================================
# SEGMENTATION
# ========================================================================================
# True, False
u_net_segmentation: False
# int [1, 5]
n_ensemble: 5

# ========================================================================================
# TENSOR DENOISING
# ========================================================================================
# True, False
uformer_denoise: False
# int: 1, 3, or 5
uformer_breatholds: 5
